### PR TITLE
fix: missing "type" in multiple attribute names

### LINKED ISSUE #6: missing `volume_type` (`volume_` typo) in block_device_mappings
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
`volume_type` is missing from `block_device_mappings`. Assuming typo is `volume_` input. Also missing `throughput` input. Will put up PR with updated code once https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/97 is merged using the new version tag. The referenced PR adds `throughput` input to the autoscale group.

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

### PR DESCRIPTION
**Pull request by esolitos**
## what

Adds the missing `_type` suffix in the following properties:
- In `block_device_mappings` the attribute `volume_` becomes `volume_type` 
- In `instance_market_options` the attribute `market_` becomes `market_type`
- In `instance_market_options` the attribute `spot_instance_` becomes `spot_instance_type`

## why

Fixes a bug where it is not possible setting up an [ec2-autoscale-group](https://github.com/cloudposse/terraform-aws-ec2-autoscale-group) with the described options.

## references

fixes #6

### CODE REVIEW

**Comment by jamengual** [comment]
please run 
```
make init
make readme
make github/init
```

**Comment by esolitos** [comment]
I updated the documentation with the suggested makes.

For now I only commited the changes to the documentation, because I wasn't sure about the changes unrelated to the current PR:
image

Let me know if I should push also those changes. 😃

**Comment by jamengual** [comment]
yes push them, those are created by the make command.

**Comment by esolitos** [comment]
👀 Opinions?

No pressure, I basically I just want to know if I should expect this to land at some point or if I should expect to just use my fork. :)

**Comment by Gowiem** [comment]
@esolitos we'll get this merged -- seems valid. Unsure if we have tests or not which is a bit confusing. Will figure that out and then we'll move it forward.

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
